services:
  - type: web
    name: shopify-tracking-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        value: write_orders,read_orders,read_fulfillments,write_themes,read_themes,write_script_tags,read_script_tags,read_products,write_products
      - key: DATABASE_URL
        value: ./database.sqlite
      - key: SESSION_SECRET
        sync: false
      - key: SHOPIFY_APP_URL
        sync: false
      - key: HOST
        sync: false
      - key: TUNNEL_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: DEV_STORE_URL
        sync: false