# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "smart-order-tracking"
client_id = "896734937b1d23f2d7e4191de83f41c6"
application_url = "https://smartordertracking.netlify.app"
embedded = true

[access_scopes]
# https://shopify.dev/docs/api/usage/access-scopes
scopes = "write_orders,read_orders,read_fulfillments,write_themes,read_themes,write_script_tags,read_script_tags,read_products,write_products"

[auth]
redirect_urls = [
  "https://shopify-tracking-backend.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false



[build]
automatically_update_urls_on_dev = true
dev_store_url = "{{ DEV_STORE_URL }}"
include_config_on_deploy = true